### Importing modules

In [3]:
import numpy as np
import sklearn
from math import log2


Creating the sub functions, so that the main function is more readable.

In [13]:
def count_labels(node):
    total_count = 0
    data_points = {}
    for point in node:
        if point not in data_points:
            data_points[point] = 1
        else:
            data_points[point] +=1
        total_count +=1
    return data_points, total_count

In [14]:
def most_label(labels):
    count_labels(labels)
    highest_label = count_labels[0]
    for label in labels:
        if label[1] > highest_label:
            highest_label = label

    return highest_label[0]

In [15]:
def one_label(data_points):
    labels = [data_points[0]]
    for d_point in data_points:
        if d_point not in labels:
            return True
    return False
        

In [23]:
def calc_prob(node):
    #Counting the labels
    data_points, total_count = count_labels(node)
    
    #Using the countings to compute the different possibilities.
    probs = []
    for point, counts in data_points.items():
        probs.append([point, counts/total_count])

    #converting to np array so the array can be sliced. 
    probs = np.array(probs)
    
    return probs

In [24]:
calc_prob([1,1,1,1,2,1,1,1,1,1])

array([[1. , 0.9],
       [2. , 0.1]])

In [27]:
def calc_impurities(node):
    probs = calc_prob(node)

    entropy = 0
    gini = 0
    misclass_rate = 0
    for prob in probs:
        entropy += -((prob[1]*log2(prob[1])))
        gini += prob[1]*(1-prob[1])
    misclass_rate = 1 - max(probs[:,1])

    return entropy, gini, misclass_rate

In [28]:
calc_impurities([1,1,1,1,2,1,1,1,1,1])

(0.4689955935892812, 0.18, 0.09999999999999998)

In [18]:
def calc_con_entropy(node, y, x):
    probs = calc_prob(node)
    cond_entropy = 0
    for prob in probs:
        #calc y given x
        y_giv_x = 
        cond_entropy += 

In [19]:
def calc_ig(node):
    return calc_entropy(node) - calc_con_entropy(node)

In [20]:
def dec_tree(root):
    if one_labels:
        return root
    

In [23]:
split_point = np.arange(8)

In [24]:
split_point

array([0, 1, 2, 3, 4, 5, 6, 7])

In [25]:
left, right = np.split(split_point, [7])

In [26]:
left

array([0, 1, 2, 3, 4, 5, 6])

In [27]:
right

array([7])